### ISSUE TITLE
(Suggestion) I think this should be a server-side mod, not a mod that is also required on the client

### ISSUE THREAD

**Issue by ghost** [Rubydesic/minecraft-dynamic-discs#6]
I have some friend that dont know how to mod, but i host the server and it would be cool if my friend could also use this mod without downloading it too.

**Comment by ghost** [comment]
I also get this error when i try to play a song: cannot run program "/home/gameserver/servers/serveur5/minecraft/dynamic-discs/youtube-dl": error=13, Permission non accordée

**Comment by Rubydesic** [comment]
it's not possible
